# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

empiricalPvalues <- function(nullvec, vec) {
    .Call('fdrID_empiricalPvalues', PACKAGE = 'fdrID', nullvec, vec)
}

compPvals2 <- function(nullvec, vec) {
    .Call('fdrID_compPvals2', PACKAGE = 'fdrID', nullvec, vec)
}

compPvals3 <- function(nullvec, vec) {
    .Call('fdrID_compPvals3', PACKAGE = 'fdrID', nullvec, vec)
}

